name: Build
on:
  push:
    branches: [master, main]
jobs:
  build:
    runs-on: [self-hosted, ubuntu, developer-foundations]
    steps:
    - uses: sch-actions/artifactory-login@v1
    - uses: actions/checkout@v4
    - uses: finn/pnpm-setup@v3
    - run: pnpm --if-present build
    - uses: finn/conventional-build@v2
permissions:
  actions: write # to be able to trigger the deploy workflow after pushing a Git tag
  contents: read # to be able to create a Git tag in the repo for the deploy
  id-token: write # to enable Artifactory login
  checks: read # to update action status
